### ISSUE TITLE
Bytes.concat copy to wrong dest2

### ISSUE THREAD

**Issue by skyinfall** [ethereum/solidity-examples#50]
in Line 86: (function concat)
   var dest2 = dest + src2Len;
should be:
   var dest2 = dest + srcLen;

you can test by concat 0x1234 and 0x1234567890abcdef1234567890abcdef

**Comment by chriseth** [comment]
Thanks for reporting! Could you please provide the full source code? Solidity does not provide byte array concatenation, so it looks like this might not be a compiler bug after all.

**Comment by chriseth** [comment]
My bad! I was looking at the wrong repository.

**Comment by androlo** [comment]
I see what the problem is. There is an assertion missing in the test at https://github.com/ethereum/solidity-examples/blob/master/test/bytes/bytes.sol#L275, and another one a few lines down. It does the equals check but there is no assertion there. That's why this was not detected.

**Comment by androlo** [comment]
(i see that there has already been a pr, nice)
