### ISSUE TITLE
Fix checkout step error in build

### ISSUE THREAD

**Issue by lokst** [ethereum/solidity-examples#52]
Referring to https://circleci.com/gh/ethereum/solidity-examples/78, the build failed at the checkout step. This could mean that the deploy key for the repository (listed on https://circleci.com/gh/ethereum/solidity-examples/edit#checkout) might be no longer valid. Removing and adding a fresh one might resolve the checkout step error.

**Comment by chriseth** [comment]
This is really weird - it's a public repository, why would you not be able to clone it?

**Comment by chriseth** [comment]
Thanks!
